AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sudoku-api

    Sudoku API Server using AWS API Gateway, Lambda functions, and DynamoDB

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Resources:
    SudokuAPIFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: sudoku-api/
            Handler: app.lambdaHandler
            Runtime: nodejs14.x
            Events:
                SudokuAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /puzzle
                        Method: get

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    SudokuAPI:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/puzzle/'
    SudokuAPIFunction:
        Description: 'Sudoku API Lambda Function ARN'
        Value: !GetAtt SudokuAPIFunction.Arn
    SudokuAPIFunctionIamRole:
        Description: 'Implicit IAM Role created for Sudoku API function'
        Value: !GetAtt SudokuAPIFunctionRole.Arn
