AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sudoku API Server using AWS API Gateway, Lambda functions, and DynamoDB

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3
    Api:
        Cors:
            AllowMethods: "'GET,OPTIONS'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"
            AllowCredentials: "'*'"

Parameters:
    DomainName:
        Type: String
        Default: sudoku-api.soffredi.org
    HostedZoneName:
        Type: String
        Default: soffredi.org.

Resources:
    SudokuAPIFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: sudoku-api/
            Handler: app.lambdaHandler
            Runtime: nodejs14.x
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref DynamoDBTable
            Events:
                SudokuAPIPuzzles:
                    Type: Api
                    Properties:
                        Path: /puzzles/{start}
                        Method: get
                        # Method: ANY
                SudokuAPIInfo:
                    Type: Api
                    Properties:
                        Path: /puzzles
                        Method: get

    APIDomainName:
        Type: AWS::ApiGateway::DomainName
        Properties:
            CertificateArn: arn:aws:acm:us-east-1:653284769887:certificate/a343fc90-7ad2-4761-8331-ddb604c99a1d
            DomainName: !Ref DomainName

    APIBasePathMapping:
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
            DomainName: !Ref APIDomainName
            RestApiId: !Ref ServerlessRestApi
            Stage: Prod

    APIDomain:
        Type: AWS::Route53::RecordSetGroup
        Properties:
            HostedZoneName: !Ref HostedZoneName
            RecordSets:
                - Name: !Ref DomainName
                  Type: A
                  AliasTarget:
                      EvaluateTargetHealth: false
                      DNSName: !GetAtt APIDomainName.DistributionDomainName
                      HostedZoneId: !GetAtt APIDomainName.DistributionHostedZoneId

    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            BillingMode: PAY_PER_REQUEST
            TableName: sudoku-puzzles
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            # ProvisionedThroughput:
            #     ReadCapacityUnits: 5
            #     WriteCapacityUnits: 5
            # StreamSpecification:
            #     StreamViewType: NEW_IMAGE

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    SudokuAPIPuzzles:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/puzzle/'
    SudokuAPIFunction:
        Description: 'Sudoku API Lambda Function ARN'
        Value: !GetAtt SudokuAPIFunction.Arn
    SudokuAPIFunctionIamRole:
        Description: 'Implicit IAM Role created for Sudoku API function'
        Value: !GetAtt SudokuAPIFunctionRole.Arn
